<a href="https://colab.research.google.com/github/flubber-lab/Beverage-Sales-Analysis/blob/main/Beverage_Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
import plotly.io as pio

In [2]:
df = pd.read_csv("/content/synthetic_beverage_sales_data.csv")
df

,Order_ID,Customer_ID,Customer_Type,Product,Category,Unit_Price,Quantity,Discount,Total_Price,Region,Order_Date
0,ORD1,CUS1496,B2B,Vio Wasser,Water,1.66,53.0,0.10,79.18,Baden-Württemberg,2023-08-23
1,ORD1,CUS1496,B2B,Evian,Water,1.56,90.0,0.10,126.36,Baden-Württemberg,2023-08-23
2,ORD1,CUS1496,B2B,Sprite,Soft Drinks,1.17,73.0,0.05,81.14,Baden-Württemberg,2023-08-23
3,ORD1,CUS1496,B2B,Rauch Multivitamin,Juices,3.22,59.0,0.10,170.98,Baden-Württemberg,2023-08-23
4,ORD1,CUS1496,B2B,Gerolsteiner,Water,0.87,35.0,0.10,27.40,Baden-Württemberg,2023-08-23
...,...,...,...,...,...,...,...,...,...,...,...
12332,ORD4152,CUS7020,B2B,Jack Daniels,Alcoholic Beverages,38.53,48.0,0.10,1664.50,Sachsen-Anhalt,2022-05-22
12333,ORD4152,CUS7020,B2B,Selters,Water,0.64,66.0,0.10,38.02,Sachsen-Anhalt,2022-05-22
12334,ORD4152,CUS7020,B2B,Havana Club,Alcoholic Beverages,33.14,99.0,0.05,3116.82,Sachsen-Anhalt,2022-05-22
12335,ORD4153,CUS7712,B2B,Augustiner,Alcoholic Beverages,2.35,96.0,0.15,191.76,Niedersachsen,2023-02-06
12336,ORD4153,CUS7712,B2B,San Pellegrino,Water,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12337 entries, 0 to 12336
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       12337 non-null  object
 1   Customer_ID    12337 non-null  object
 2   Customer_Type  12337 non-null  object
 3   Product        12337 non-null  object
 4   Category       12337 non-null  object
 5   Unit_Price     12336 non-null  float64
 6   Quantity       12336 non-null  float64
 7   Discount       12336 non-null  float64
 8   Total_Price    12336 non-null  float64
 9   Region         12336 non-null  object
 10  Order_Date     12336 non-null  object
dtypes: float64(4), object(7)
memory usage: 1.0+ MB

In [4]:
df.isnull().sum()

Order_ID         0
Customer_ID      0
Customer_Type    0
Product          0
Category         0
Unit_Price       1
Quantity         1
Discount         1
Total_Price      1
Region           1
Order_Date       1
dtype: int64

In [5]:
df.dropna(axis=0, inplace=True)

In [8]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"], format="%d-%m-%Y")

In [9]:
df["Order_Date"].dtype

dtype('<M8[ns]')

In [10]:
df.describe()

,Unit_Price,Quantity,Discount,Total_Price,Order_Date
count,12336.000000,12336.000000,12336.000000,12336.000000,12336
mean,5.696627,23.126540,0.029442,125.106450,2022-07-12 20:14:07.470817024
min,0.320000,1.000000,0.000000,0.390000,2021-01-01 00:00:00
25%,1.070000,6.000000,0.000000,8.640000,2021-10-15 00:00:00
50%,1.770000,11.000000,0.000000,21.140000,2022-07-19 00:00:00
75%,3.192500,30.000000,0.050000,69.037500,2023-04-13 00:00:00
max,132.090000,100.000000,0.150000,10112.850000,2023-12-30 00:00:00
std,14.511984,26.821238,0.044605,484.456831,NaN

In [11]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Type', 'Product', 'Category',
       'Unit_Price', 'Quantity', 'Discount', 'Total_Price', 'Region',
       'Order_Date'],
      dtype='object')

In [13]:
qty = df.groupby(["Product", "Category"])["Quantity"].sum().reset_index()

In [12]:
pip install -U Kaleido

Collecting Kaleido
  Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl.metadata (15 kB)
Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl (79.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 12.6 MB/s eta 0:00:00
Installing collected packages: Kaleido
Successfully installed Kaleido-0.2.1

In [14]:
fig = px.bar(qty, x ='Product', y='Quantity',color='Category',title='Sales Quantity by Product')
fig.show()
fig.write_image("Sales_quantity_by_product.png")

In [15]:
fig1=px.pie(qty, values='Quantity', names='Category',hole=0.3 ,
       title='Sales Quantity by Category', color_discrete_sequence=px.colors.qualitative.Pastel)
fig1.show()
fig1.write_image("Sales_quantity_by_category.png")

In [16]:
rgn = df.groupby(["Region","Category","Product"]).agg({'Quantity':'sum','Total_Price':'sum'}).reset_index()
rgn

,Region,Category,Product,Quantity,Total_Price
0,Baden-Württemberg,Alcoholic Beverages,Augustiner,151.0,213.67
1,Baden-Württemberg,Alcoholic Beverages,Bacardi,194.0,5688.93
2,Baden-Württemberg,Alcoholic Beverages,Beck's,68.0,85.72
3,Baden-Württemberg,Alcoholic Beverages,Chardonnay,349.0,2619.33
4,Baden-Württemberg,Alcoholic Beverages,Erdinger Weißbier,224.0,437.87
...,...,...,...,...,...
747,Thüringen,Water,Selters,672.0,413.81
748,Thüringen,Water,Vio Wasser,391.0,481.02
749,Thüringen,Water,Vittel,634.0,413.23
750,Thüringen,Water,Volvic,603.0,451.80
751,Thüringen,Water,Volvic Touch,367.0,387.98

In [17]:
fig2 = px.bar(rgn, x='Region',y='Quantity',color='Category',barmode='stack'
,color_discrete_sequence=px.colors.qualitative.Pastel, title='Sales Quantity by Region')
fig2.show()
fig2.write_image("Sales_quantity_by_region.png")

In [31]:
price = df.groupby(['Category','Product'])['Total_Price'].sum().reset_index()
fig3 = px.bar(price, x='Product', y='Total_Price', color='Category',
              title='Total Sales by Product', color_discrete_sequence=px.colors.qualitative.Pastel,
              labels={'Product':'Product','Total_Price':'Total Sales'})
fig3.show()
fig3.write_image("Total_sales_by_product.png")

In [46]:
fig4=px.pie(price, names='Category', values='Total_Price', hole=0.3,
       title='Most Selling Category', color_discrete_sequence=px.colors.qualitative.Safe)
fig4.show()
fig4.write_image("Most_selling_category.png")